---
- name: Create Azure Resource Group
  azure_rm_resourcegroup:
    name: "{{ az_resource_group_name }}"
    location: "{{ az_resource_group_location }}"
    state: "present"
    tenant: "{{ azure_tenant_id }}"
    subscription_id: "{{ azure_subscription_id }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    tags: "{{ az_tags_dict }}"
...
